name: managed

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'lib/**'
    - '*.md'
    - '*.txt'
  pull_request:

jobs:
  build:
    uses: xoofx/.github/.github/workflows/dotnet.yml@main
    with:
        dotnet-version: 7.0
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}      