name: native

on:
  push:
    paths-ignore:
    - 'lib/native'
    - 'src/**'
    - '*.md'
    - '*.txt'
  pull_request:

defaults:
  run:
    working-directory: lib/blake3_dotnet

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
          chmod 755 *.sh
          echo "building linux-x64"
          ./build-linux-x64.sh
          echo "building linux-arm64"
          sudo apt-get install gcc-aarch64-linux-gnu      
          ./build-linux-arm64.sh
          echo "building linux-arm"
          sudo apt-get install gcc-arm-linux-gnueabihf      
          ./build-linux-arm.sh
    - name: Build macOS
      if: matrix.os == 'macOS-latest'
      run: |
          chmod 755 *.sh
          ./build-osx-x64.sh
#          ./build-osx-arm64.sh
    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: |
          ./build-win-x64.ps1
          ./build-win-x86.ps1
          ./build-win-arm64.ps1
#          ./build-win-arm.ps1
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-${{ matrix.os }}
        path: lib/blake3_dotnet/build/